name: Node.js CI
on: [push]
jobs:
  build:
    name: Node.js ${{ matrix.node-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, ls, and test
      run: |
        npm install
        npm ls
        npm test
      env:
        CI: true
